# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Model Compression
email: wangzs611@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Add describtions later !
baseurl: /Neural-Network-Notes
url: "https://zhishengwang.github.io/" # the base hostname & protocol for your site
twitter_username: None
github_username:  ZhishengWang

# Build settings
markdown: kramdown
